### ISSUE TITLE
any way to render a loading view

### ISSUE THREAD

**Issue by geohuz** [cyclejs/cycle-http-driver#45] opened 2016-02-11 04:21 UTC
I'm wondering if I can render a spinner use startWith only output text?

**Comment by staltz** [comment] 2016-02-18 20:10
Hi, this seems to be general Cycle.js question, not a bug in the HTTP Driver, so I recommend you check in the gitter channel. I'll close this, sorry

**Closed by staltz** 2016-02-18 20:10 UTC
